- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "dependencies"
  color: "fbca04"
  description: "Update of dependencies"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "enhancement"
  color: "008672"
  description: "New feature or request"
- name: "size/XS"
  color: "0e8a16"
  description: "PR with minimal changes"
- name: "size/S"
  color: "0EFABD"
  description: "PR with small changes"
- name: "size/M"
  color: "75CEF4"
  description: "PR with medium changes"
- name: "size/L"
  color: "FBCA04"
  description: "PR with large changes"
- name: "size/XL"
  color: "B60205"
  description: "PR with very large changes"
