---
name: Auto-approve PR

on:
  pull_request:

jobs:
  approve:
    name: Approve

    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-22.04

    steps:
      - name: Wait for status checks
        id: waitforstatuschecks
        uses: WyriHaximus/github-action-wait-for-status@v1.8.0
        with:
          ignoreActions: Approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve Pull Request
        uses: hmarr/auto-approve-action@v4.0.0
        if: steps.waitforstatuschecks.outputs.status == 'success'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
