---
name: Pull Request lint

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  pr-lint:
    name: Pull Request lint

    # Workflow should not run when Dependabot is opening it
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-22.04

    steps:
      - name: Lint Pull Request title
        uses: morrisoncole/pr-lint-action@v1.7.1
        with:
          title-regex: "(?:UII|UISD)-[0-9]+"
          on-failed-regex-fail-action: true
          on-failed-regex-comment:
            "Please adjust the title of the PR to include the correct ticket number. Failed regex: `%regex%`!"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
